laundry/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('services.urls')),
]

services/urls.py
from django.urls import path
from .import views

urlpatterns = [
    path('',views.index, name='index'),
    path('logput',views.logout, name='logout'),
    path('dashboard',views.dashboard, name='dashboard'),

    # Service Views
    path('addservice', views.add_service, name='add-service'),
    path('servicelist', views.service_list, name='service-list'),
    path('editservice/<int:id>', views.edit_service, name='edit-service'),
    path('deleteservice/<int:id>', views.delete_service, name='delete-service'),

    # Customer Views
    path('addcustomer', views.add_customer, name='add-customer'),
    path('customerlist', views.customer_list, name='customer-list'),
    path('editcustomer/<int:id>', views.edit_customer, name='edit-customer'),
    path('deletecustomer/<int:id>', views.delete_customer, name='delete-customer'),
    path('assignservice', views.assign_service, name='assign-service'),

    # Fuller Views

    path('addfuller', views.add_fuller, name='add-fuller'),
    path('fullerlist', views.fuller_list, name='fuller-list'),
    path('editfuller/<int:id>', views.edit_fuller, name='edit-fuller'),
    path('deletefuller/<int:id>', views.delete_fuller, name='delete-fuller'),

    # Invice Views
    path('invoicelist', views.invoice_list, name='invoice-list'),
    path('viewinvoice/<int:id>', views.view_invoice, name='view-invoice'),
    path('deleteinvoice/<int:id>', views.delete_invoice, name='delete-invoice'),

]

services/models.py
from django.db import models
from django.contrib.auth.models import User
from multiselectfield import MultiSelectField

class Service(models.Model):
    id=models.AutoField(primary_key=True)
    name=models.CharField(max_length=30,null=True)
    cost=models.FloatField(null=True)
    created_date=models.DateField(auto_now_add=True)

    def __str__(self):
        return self.name
class Customer(models.Model):
    Sex_Choice=(
    (1,'Male'),
    (2,'Famale')
    )
    id=models.AutoField(primary_key=True)
    name=models.CharField(max_length=30, null=True)
    age=models.IntegerField()
    sex= models.PositiveSmallIntegerField(choices=Sex_Choice, null= True,)
    mobile=models.CharField(max_length=20, null=True, unique=True)
    description=models.TextField(null=True, blank=True)
    created_date=models.DateField(auto_now_add=True)

    def __str__(self):
        return self.name

class Fuller(models.Model):
    Days_CHOICES = (('Sun', 'Sun'),
              ('Mon', 'Mon'),
              ('Tue', 'Tue'),
              ('Wed', 'Wed'),
              ('Thu', 'Thu'),
              ('Fri', 'Fri'),
              ('Sat', 'Sat'),
              )
    id=models.AutoField(primary_key=True)
    name=models.CharField(max_length=30, null=True)
    speciality=models.CharField(max_length=30, null=True)
    salary=models.FloatField()
    from_time=models.TimeField()
    to_time=models.TimeField()
    days = MultiSelectField(choices=Days_CHOICES)
    created_date=models.DateField(auto_now_add=True)

    def __str__(self):
        return self.name

class Assignservice(models.Model):
    id= models.AutoField(primary_key=True)
    customer=models.ForeignKey(Customer,on_delete=models.CASCADE)
    fuller=models.ForeignKey(Fuller, on_delete=models.SET_NULL, null=True)
    total=models.CharField(max_length=100, null=True, blank=True)
    discount=models.CharField(max_length=100, null=True, blank=True)
    grandtotal=models.CharField(max_length=100,null=True, blank=True)
    delivery_date=models.DateField(null=True, blank=True)

class Assignservice_detail(models.Model):
    id= models.AutoField(primary_key=True)
    assign=models.ForeignKey(Assignservice, on_delete=models.CASCADE, null=True)
    service=models.ForeignKey(Service, on_delete=models.SET_NULL, null=True)
    quantity=models.IntegerField()

services/forms.py
from django import forms
from bootstrap_datepicker_plus import TimePickerInput
from .models import Service, Customer, Fuller, Assignservice, Assignservice_detail

class ServiceForms(forms.ModelForm):
    name=forms.CharField(max_length=30,)
    cost=forms.FloatField(help_text='Service Cost in USD')
    class Meta:
        model=Service
        fields=('name','cost')

class CustomerForms(forms.ModelForm):
    age=forms.FloatField(help_text='Age in years')
    class Meta:
        model=Customer
        fields=('name','age','sex','mobile','description')

class FullerForms(forms.ModelForm):
    salary=forms.FloatField(help_text='Salary in USD')
    class Meta:
        model=Fuller
        fields=['name','speciality','salary','days','from_time','to_time']
        widgets = {
            'from_time':TimePickerInput().start_of('party time'),
            'to_time':TimePickerInput().end_of('party time'),
        }

class AssignserviceForm(forms.ModelForm):
    class Meta:
        model=Assignservice
        fields= ('__all__')

class Assignservice_detailForm(forms.ModelForm):
    class Meta:
        fields= ('__all__')

services/views.py
from django.shortcuts import render, HttpResponse, redirect, get_object_or_404
from django.contrib.auth.models import User
from django.utils import timezone as tz
from django.contrib.auth import login, authenticate, logout as auth_logout
from django.contrib.auth.decorators import login_required
from .forms import ServiceForms, CustomerForms, FullerForms, AssignserviceForm, Assignservice_detailForm
from .models import Service, Customer, Fuller, Assignservice, Assignservice_detail
from django.contrib import messages

def index(request):
    if request.method=='POST':
        username= request.POST.get('username')
        password= request.POST.get('password')
        user= authenticate(username=username, password=password)
        if user is not None:
            login(request,user)
            return redirect('dashboard')
        else:
            messages.error(request,'Username or Password is Wrong')
    return render(request,'services/index.html')
@login_required(login_url='/')
def dashboard(request):
    return render(request,'services/dashboard.html')

@login_required(login_url='/')
def add_service(request):
    if request.method =='POST':
        add_form= ServiceForms(request.POST)
        if add_form.is_valid():
            add_form.save()
            servicename=request.POST.get('name')
            messages.success(request,f'{servicename} service has been added successfully.')
            return redirect('service-list')
        else:
            messages.error(request,'Something Wrong.')
    add_form=ServiceForms()
    return render(request,'services/addservice.html', {'add_form':add_form})

@login_required(login_url='/')
def service_list(request):
    services=Service.objects.all().order_by('-id')
    return render(request,'services/servicelist.html',{'services':services})

@login_required(login_url='/')
def edit_service(request,id):
    obj=Service.objects.filter(id=id).first()
    if request.method == 'POST':
        edit_form = ServiceForms(request.POST,instance=obj)
        if edit_form.is_valid():
            edit_form.save()
            messages.success(request, 'Records have been updated successfully.')
            return redirect('service-list')
    else:
        edit_form=ServiceForms(instance=obj)
    return render(request,'services/editservice.html',{'edit_form':edit_form})

@login_required(login_url='/')
def delete_service(request, id):
    obj=Service.objects.filter(id=id).delete()
    if obj:
        return redirect('service-list')

@login_required(login_url='/')
def add_customer(request):
    if request.method == 'POST':
        customer_form = CustomerForms(request.POST)
        if customer_form.is_valid():
            customer_form.save()
            cname=request.POST.get('name')
            messages.success(request,f'{cname} has been added successfully as customer.')
            return redirect('customer-list')
        else:
            messages.error(request,'Mobile Number Must Unique.')
            return redirect('customer-list')
    customer_form = CustomerForms()
    return render(request,'services/addcustomer.html',{'customer_form':customer_form})

@login_required(login_url='/')
def customer_list(request):
    customers=Customer.objects.all().order_by('-id')
    return render(request,'services/customerlist.html',{'customers':customers})

@login_required(login_url='/')
def edit_customer(request,id):
    obj=Customer.objects.filter(id=id).first() #  get single objects
    if request.method == 'POST':
        edit_form = CustomerForms(request.POST,instance=obj)
        if edit_form.is_valid():
            edit_form.save()
            messages.success(request, 'Records have been updated successfully.')
            return redirect('customer-list')
    else:
        edit_form=CustomerForms(instance=obj)
    return render(request,'services/editcustomer.html',{'edit_form':edit_form})

@login_required(login_url='/')
def delete_customer(request, id):
    obj=Customer.objects.filter(id=id).delete()
    if obj:
        return redirect('customer-list')

@login_required(login_url='/')
def add_fuller(request):
    if request.method == 'POST':
        fuller_form= FullerForms(request.POST)
        if fuller_form.is_valid():
            fuller_form.save()
            fullername=request.POST.get('name')
            messages.success(request, f'{fullername} has been added successfully as Fuller.')
            return redirect('fuller-list')
        else:
            messages.error(request, 'Something Wrong.')
    fuller_form= FullerForms()
    return render(request, 'services/addfuller.html',{'fuller_form':fuller_form})

@login_required(login_url='/')
def fuller_list(request):
    fullers= Fuller.objects.all().order_by('-id')
    return render(request,'services/fullerlist.html',{'fullers':fullers})

@login_required(login_url='/')
def edit_fuller(request,id):
    obj=Fuller.objects.filter(id=id).first() # get single objects
    if request.method == 'POST':
        edit_form= FullerForms(request.POST, instance=obj)
        if edit_form.is_valid():
            edit_form.save()
            messages.success(request, 'Fuller has been updated successfully.')
            return redirect('fuller-list')
    else:
        edit_form = FullerForms(instance=obj)
    return render(request, 'services/editfuller.html',{'edit_form':edit_form})

@login_required(login_url='/')
def delete_fuller(request,id):
    delfuller=Fuller.objects.filter(id=id).delete()
    if delfuller:
        return redirect('fuller-list')

@login_required(login_url='/')
def assign_service(request):
    services=Service.objects.all()
    customers=Customer.objects.all()
    fullers=Fuller.objects.all()
    data={'customers':customers,'fullers':fullers, 'services':services}
    if request.method == 'POST':
        customer_id=request.POST.get('customer_id')
        fuller_id=request.POST.get('fuller_id')
        total=request.POST.get('totalinput')
        discount=request.POST.get('discount')
        grandtotal=request.POST.get('gtotalinput')
        delivery_date=request.POST.get('delivery_date')
        assignservice=Assignservice(customer_id=customer_id,fuller_id=fuller_id,total=total,discount=discount,grandtotal=grandtotal,delivery_date=delivery_date);
        assignservice.save()
        assign_service=request.POST.getlist('service[]')
        id = Assignservice.objects.latest('id') # get last inserted id
        assign_id=id.id
        status=False
        for i in assign_service:
            print(assign_id)
            service_id=i
            quantity=request.POST.get('q'+i)
            assignervice_detail=Assignservice_detail(service_id=service_id,quantity=quantity,assign_id=assign_id)
            assignervice_detail.save()
            status=True
        if status==True:
            messages.success(request, 'Assign services successfully to customer.')
        else:
            message.error('Somethong Wrong.')

    return render(request,'services/assignservice.html',data)

@login_required(login_url='/')
def invoice_list(request):
    assign_services=Assignservice.objects.all().order_by('-id')
    return render(request,'services/invoicelist.html',{'assign_services':assign_services})

@login_required(login_url='/')
def view_invoice(request,id):
    assign_services=Assignservice.objects.filter(id=id)
    today_date=tz.now();
    assign_service_details=Assignservice_detail.objects.filter(assign_id=id)
    return render(request,'services/viewinvoice.html',{'assign_services':assign_services,'today_date':today_date,'assign_service_details':assign_service_details})

@login_required(login_url='/')
def delete_invoice(request,id):
    delassignservice=Assignservice.objects.filter(id=id).delete()
    if delassignservice:
        return redirect('invoice-list')

def logout(request):
    auth_logout(request)
    return redirect('index')

services/templates/services/addcustomer.html
{%extends 'services/base.html'%}
{% block container%}
{% load crispy_forms_tags %}
<!-- Content Header (Page header) -->
<div class="content-header">
  <div class="container-fluid">
    <div class="row mb-2">
      <div class="col-sm-6">
        <h1 class="m-0 text-dark">Customer Section</h1>
      </div><!-- /.col -->
      <div class="col-sm-6">
        <ol class="breadcrumb float-sm-right">
          <li class="breadcrumb-item"><a href="{% url 'dashboard'%}">Dashboard</a></li>
          <li class="breadcrumb-item active">Add New Customer</li>
        </ol>
      </div><!-- /.col -->
    </div><!-- /.row -->
  </div><!-- /.container-fluid -->
</div>
<!-- /.content-header -->

<!-- Main content -->
<section class="content">
  <div class="container-fluid">
    <!-- Small boxes (Stat box) -->
    <div class="row">
      <div class="col-lg-12 col-12">
        <div class="card card-info">
              <div class="card-header">
                <h3 class="card-title">Add New Customer</h3>
              </div>
              <form class="" action="{% url 'add-customer'%}" method="post">{%csrf_token%}
                 <div class="card-body">
                  {{customer_form|crispy}}
                  <!-- /.card-body -->
                  </div>
                  <div class="card-footer">
                      <button type="submit" class="btn btn-primary">Add Customer</button>
                  </div>
              </form>
            </div>
      </div>
      <!-- ./col -->
    </div>
    <!-- /.row -->

  </div><!-- /.container-fluid -->
</section>
<!-- /.content -->
{% endblock %}

services/templates/services/addfuller.html
{%extends 'services/base.html'%}
{% block container%}
{% load crispy_forms_tags %}
{% load bootstrap4 %}       {# import bootstrap4/bootstrap3 #}
{% bootstrap_css %}         {# Embed Bootstrap CSS #}
{% bootstrap_javascript jquery='full' %}  {# Embed Bootstrap JS+jQuery #}
{{ fuller_form.media }}            {# Adds date-picker required JS and CSS #}
<!-- Content Header (Page header) -->
<div class="content-header">
  <div class="container-fluid">
    <div class="row mb-2">
      <div class="col-sm-6">
        <h1 class="m-0 text-dark">Washerman Section</h1>
      </div><!-- /.col -->
      <div class="col-sm-6">
        <ol class="breadcrumb float-sm-right">
          <li class="breadcrumb-item"><a href="{% url 'dashboard'%}">Dashboard</a></li>
          <li class="breadcrumb-item active">Add New Fuller</li>
        </ol>
      </div><!-- /.col -->
    </div><!-- /.row -->
  </div><!-- /.container-fluid -->
</div>
<!-- /.content-header -->

<!-- Main content -->
<section class="content">
  <div class="container-fluid">
    <!-- Small boxes (Stat box) -->
    <div class="row">
      <div class="col-lg-12 col-12">
        <div class="card card-info">
              <div class="card-header">
                <h3 class="card-title">Add New Fuller</h3>
              </div>
              <form class="" action="{% url 'add-fuller'%}" method="post">{%csrf_token%}
                 <div class="card-body">
                  {{fuller_form|crispy}}
                  <!-- /.card-body -->
                  </div>
                  <div class="card-footer">
                      <button type="submit" class="btn btn-primary">Add Fuller</button>
                  </div>
              </form>
            </div>
      </div>
      <!-- ./col -->
    </div>
    <!-- /.row -->

  </div><!-- /.container-fluid -->
</section>
<!-- /.content -->
{% endblock %}

services/templates/services/addservice.html
{%extends 'services/base.html'%}
{% block container%}
{% load crispy_forms_tags %}
<!-- Content Header (Page header) -->
<div class="content-header">
  <div class="container-fluid">
    <div class="row mb-2">
      <div class="col-sm-6">
        <h1 class="m-0 text-dark">Service Section</h1>
      </div><!-- /.col -->
      <div class="col-sm-6">
        <ol class="breadcrumb float-sm-right">
          <li class="breadcrumb-item"><a href="{% url 'dashboard'%}">Dashboard</a></li>
          <li class="breadcrumb-item active">Add New Service</li>
        </ol>
      </div><!-- /.col -->
    </div><!-- /.row -->
  </div><!-- /.container-fluid -->
</div>
<!-- /.content-header -->

<!-- Main content -->
<section class="content">
  <div class="container-fluid">
    <!-- Small boxes (Stat box) -->
    <div class="row">
      <div class="col-lg-12 col-12">
        <div class="card card-info">
              <div class="card-header">
                <h3 class="card-title">Add New Service</h3>
              </div>
              <form class="" action="{% url 'add-service'%}" method="post">{%csrf_token%}
                 <div class="card-body">
                  {{add_form|crispy}}
                  <!-- /.card-body -->
                  </div>
                  <div class="card-footer">
                      <button type="submit" class="btn btn-primary">Add Service</button>
                  </div>
              </form>
            </div>
      </div>
      <!-- ./col -->
    </div>
    <!-- /.row -->

  </div><!-- /.container-fluid -->
</section>
<!-- /.content -->
{% endblock %}

services/templates/services/assignservice.html
{%extends 'services/base.html'%}
{% block container%}
{% load crispy_forms_tags %}
<!-- Content Header (Page header) -->
<div class="content-header">
  <div class="container-fluid">
    <div class="row mb-2">
      <div class="col-sm-6">
        <h1 class="m-0 text-dark">Assign Service Section</h1>
      </div><!-- /.col -->
      <div class="col-sm-6">
        <ol class="breadcrumb float-sm-right">
          <li class="breadcrumb-item"><a href="{% url 'dashboard'%}">Dashboard</a></li>
          <li class="breadcrumb-item active">Assign Service</li>
        </ol>
      </div><!-- /.col -->
    </div><!-- /.row -->
  </div><!-- /.container-fluid -->
</div>
<!-- /.content-header -->

<!-- Main content -->
<section class="content">
  <div class="container-fluid">
    <!-- Small boxes (Stat box) -->
    <div class="row">
      <div class="col-lg-12 col-12">
        <div class="card card-info">
              <div class="card-header">
                <h3 class="card-title">Assign Service</h3>
              </div>
              <form class="" action="{% url 'assign-service'%}" method="post">{%csrf_token%}
                 <div class="card-body">
                   <div id="div_id_customer" class="form-group">
                     <label for="id_customer" class="col-form-label  requiredField">Customer Name<span class="asteriskField">*</span> </label>
                     <div class="">
                       <select class="form-control customer customer-hidden-accessible" name="customer_id" style="width: 100%;" data-customer-id="1" tabindex="-1" aria-hidden="true">
                         {% for customer in customers%}
                        <option selected="selected" data-customer-id="{{customer.id}}" value="{{customer.id}}">{{customer.name}}</option>
                        {% endfor %}
                      </select>
                     </div>
                   </div>
                   <div id="div_id_fuller" class="form-group">
                     <label for="id_fuller" class="col-form-label  requiredField">Fuller Name<span class="asteriskField">*</span> </label>
                     <div class="">
                       <select class="form-control fuller fuller-hidden-accessible" name="fuller_id" style="width: 100%;" data-fuller-id="1" tabindex="-1" aria-hidden="true">
                        {% for fuller in fullers%}
                        <option data-fuller-id="{{fuller.id}}" value="{{fuller.id}}">{{fuller.name}}</option>
                        {% endfor %}
                      </select>
                     </div>
                   </div>
                <!-- table start -->
                <div class="row">
                  <div class="col-md-8">
                    <div class="card-body p-0">
                    <table class="table table-condensed">
                      <tbody>
                      <tr>
                        <th style="width: 15%">#</th>
                        <th  style="width: 60%">Services</th>
                        <th style="width:25%">Quantity</th>
                      </tr>
                      {% for service in services%}
                      <tr>
                        <td style="width: 15%">
                          <input type="checkbox" onchange="check()" id="assignservice{{service.id}}" class="assignservice" value="{{service.id}}" name="service[]" />
                        </td>
                        <td style="width: 60%">{{service.name}}</td>
                        <td style="width:25%">
                          <input type="hidden" name="c{{service.id}}" id="c{{service.id}}" value="{{service.cost}}">
                          <input type="number" id='q{{service.id}}' name='q{{service.id}}' value='1' onchange="check()" disabled>
                        </td>
                      </tr>
                      {% endfor %}
                    </tbody></table>
                  </div>
                  </div>
                  <div class="col-md-4">
                    <div class="card-body p-0">
                    <table class="table table-condensed">
                      <tbody>
                      <tr>
                        <th>Total</th>
                      </tr>
                      <tr>
                        <td><span id="total">0.0</span> USD</td>
                        <input type="hidden" name="totalinput" value="" id="totalinput">
                      </tr>
                      <tr>
                        <th>Discount</th>
                      </tr>
                      <tr>
                        <td><input type="text" class="form-control" id="discount" name= "discount" onchange="Mydiscount()" placeholder=" e.g: 100"></td>
                      </tr>
                      <tr>
                        <th>Grand Total</th>
                      </tr>
                      <tr>
                        <td><span id="gtotal">0.00</span> USD</td>
                        <input type="hidden" name="gtotalinput" value="" id="gtotalinput">
                      </tr>
                      <tr>
                        <th>Delivery Date</th>
                      </tr>
                      <tr>
                        <td>
                          <input type='text' class="form-control" id='datepicker' name="delivery_date" autocomplete="off"/>
                        </td>
                      </tr>
                      <tr>
                        <td><button type="submit" class="btn btn-primary">Assign Service</button></td>
                      </tr>
                    </tbody></table>
                  </div>
                  </div>
                </div>

                   <!-- </table end> -->
                  <!-- /.card-body -->
                  </div>
              </form>
            </div>
      </div>
      <!-- ./col -->
    </div>
    <!-- /.row -->

  </div><!-- /.container-fluid -->
</section>
<!-- /.content -->
{% endblock %}
{% block javascript %}
<script>
    $(document).ready(function(){
      //Initialize Select2 Elements
      $('.customer').select2()
      $('.fuller').select2()
      $('#example2').DataTable({
        "paging": true,
        "lengthChange": false,
        "searching": false,
        "ordering": true,
        "info": true,
        "autoWidth": false,
      });
});
 // Calculate Amount of services

 $('.assignservice').click(function() {
        var idser=this.id;
        var a=this.id.slice(13,)
        var as= $('#assignservice'+a).is(':checked');
        $('#q'+a).prop('disabled', !(as));
		});

function check()
{ var idstr, a, add=0;
  $('input[type=checkbox]').each(function (){
     idser = $(this).attr("id");
     if(typeof idser !== "undefined"){
       var a=idser.slice(13,)
       if(document.getElementById('assignservice'+a).checked) {
       	add += document.getElementById('c'+a).value * document.getElementById('q'+a).value;
        }
        var p = add;
        var price = p;
        document.getElementById('total').innerHTML = price;
        document.getElementById('totalinput').value = price;
        document.getElementById('gtotal').innerHTML = price;
        document.getElementById('gtotalinput').value = price;
      }
  });
}

function Mydiscount(){
  var grandtotal;
  var discount=document.getElementById("discount").value;
  if (discount > 0){
    var total=document.getElementById("total").innerHTML;
    if(parseFloat(total) > parseFloat(discount)){
    grandtotal= parseFloat(total) - parseFloat(discount);
    document.getElementById('gtotal').innerHTML = grandtotal;
    document.getElementById('gtotalinput').value = grandtotal;
    }
    else{
      alert('You can not give discount more than total cost.')
      document.getElementById('gtotal').innerHTML = total;
      document.getElementById('gtotalinput').value = total;
    }

  }
}
$(document).ready(function(){
  $('#datepicker').datepicker({
      dateFormat: "yy-mm-dd"
  });
});

</script>
{% endblock %}

services/templates/services/customerlist.html
{%extends 'services/base.html'%}
{% block container%}
     <div class="container-fluid">
       <div class="row mb-2">
         <div class="col-sm-6">
           <h1>Customer List</h1>
         </div>
         <div class="col-sm-6">
           <ol class="breadcrumb float-sm-right">
             <li class="breadcrumb-item"><a href="{% url 'dashboard'%}">Home</a></li>
             <li class="breadcrumb-item active">Customer List</li>
           </ol>
         </div>
       </div>
     </div><!-- /.container-fluid -->
   </section>

   <!-- Main content -->
   <section class="content">
     <div class="row">
       <div class="col-12">
         <div class="card">
         <!-- /.card-header -->
           <div class="card-body">
             <table id="example1" class="table table-bordered table-striped">
               <thead>
               <tr>
                 <th>Sr. No.</th>
                 <th>Name</th>
                 <th>Age (Year)</th>
                 <th>Sex</th>
                 <th>Mobile</th>
                 <th>Created Date</th>
                 <th>Action</th>
               </tr>
               </thead>
               <tbody>
              {% for customer in customers %}
               <tr>
                 <td>{{forloop.counter}}</td>
                 <td>{{customer.name}}</td>
                 <td>{{customer.age}}</td>
                 <td>{% if customer.sex == 1 %}Male {% else %} Female {%endif%}</td>
                 <td>{{customer.mobile}}</td>
                 <td>{{customer.created_date}}</td>
                 <td>
                   <a href="{% url 'edit-customer' id=customer.id%}">Edit</a> |
                   <a href="{% url 'delete-customer' id=customer.id%}" onclick="return confirm('Are you want to delete this customer.')">Delete</a>
                 </td>
               </tr>
               {% endfor %}
               </tbody>
               <tfoot>
               <tr>
                 <th>Sr. No.</th>
                 <th>Name</th>
                 <th>Age</th>
                 <th>Sex</th>
                 <th>Mobile</th>
                 <th>Created Date</th>
                 <th>Action</th>
               </tr>
               </tfoot>
             </table>
           </div>
           <!-- /.card-body -->
         </div>
         <!-- /.card -->
       </div>
       <!-- /.col -->
     </div>
     <!-- /.row -->
   </section>
   <!-- /.content -->
{% endblock %}

services/templates/services/editcustomer.html
{%extends 'services/base.html'%}
{% block container%}
{% load crispy_forms_tags %}
<!-- Content Header (Page header) -->
<div class="content-header">
  <div class="container-fluid">
    <div class="row mb-2">
      <div class="col-sm-6">
        <h1 class="m-0 text-dark">Customer Section</h1>
      </div><!-- /.col -->
      <div class="col-sm-6">
        <ol class="breadcrumb float-sm-right">
          <li class="breadcrumb-item"><a href="{% url 'dashboard'%}">Dashboard</a></li>
          <li class="breadcrumb-item active">Edit Customer</li>
        </ol>
      </div><!-- /.col -->
    </div><!-- /.row -->
  </div><!-- /.container-fluid -->
</div>
<!-- /.content-header -->

<!-- Main content -->
<section class="content">
  <div class="container-fluid">
    <!-- Small boxes (Stat box) -->
    <div class="row">
      <div class="col-lg-12 col-12">
        <div class="card card-info">
              <div class="card-header">
                <h3 class="card-title">Edit Customer</h3>
              </div>
              <form action="" method="post">{%csrf_token%}
                 <div class="card-body">
                  {{edit_form|crispy}}
                  <!-- /.card-body -->
                  </div>
                  <div class="card-footer">
                      <button type="submit" class="btn btn-primary">Update Customer</button>
                  </div>
              </form>
            </div>
      </div>
      <!-- ./col -->
    </div>
    <!-- /.row -->

  </div><!-- /.container-fluid -->
</section>
<!-- /.content -->
{% endblock %}

services/templates/services/editservice.html
{%extends 'services/base.html'%}
{% block container%}
{% load crispy_forms_tags %}
<!-- Content Header (Page header) -->
<div class="content-header">
  <div class="container-fluid">
    <div class="row mb-2">
      <div class="col-sm-6">
        <h1 class="m-0 text-dark">Service Section</h1>
      </div><!-- /.col -->
      <div class="col-sm-6">
        <ol class="breadcrumb float-sm-right">
          <li class="breadcrumb-item"><a href="{% url 'dashboard'%}">Dashboard</a></li>
          <li class="breadcrumb-item active">Edit Service</li>
        </ol>
      </div><!-- /.col -->
    </div><!-- /.row -->
  </div><!-- /.container-fluid -->
</div>
<!-- /.content-header -->

<!-- Main content -->
<section class="content">
  <div class="container-fluid">
    <!-- Small boxes (Stat box) -->
    <div class="row">
      <div class="col-lg-12 col-12">
        <div class="card card-info">
              <div class="card-header">
                <h3 class="card-title">Edit Service</h3>
              </div>
              <form action="" method="post">{%csrf_token%}
                 <div class="card-body">
                  {{edit_form|crispy}}
                  <!-- /.card-body -->
                  </div>
                  <div class="card-footer">
                      <button type="submit" class="btn btn-primary">Update Service</button>
                  </div>
              </form>
            </div>
      </div>
      <!-- ./col -->
    </div>
    <!-- /.row -->

  </div><!-- /.container-fluid -->
</section>
<!-- /.content -->
{% endblock %}